name = "next-cf-app"
main = "worker.ts"
compatibility_date = "2025-03-01"
compatibility_flags = [
    "nodejs_compat",
    "global_fetch_strictly_public",
    "nodejs_als",
]
upload_source_maps = true

[assets]
    binding = "ASSETS"
    directory = ".open-next/assets"

[observability]
    enabled = true


[[d1_databases]]
    binding = "next_cf_app"
    database_name = "next-cf-app"
    database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
    migrations_dir = "./src/drizzle"

[[r2_buckets]]
    binding = "next_cf_app_bucket"
    bucket_name = "next-cf-app-bucket"

[[r2_buckets]]
    binding = "NEXT_INC_CACHE_R2_BUCKET"
    bucket_name = "next-cf-app-inc-cache"

[durable_objects]
    bindings = [
        { name = "NEXT_CACHE_DO_QUEUE", class_name = "DOQueueHandler" },
        { name = "NEXT_TAG_CACHE_DO_SHARDED", class_name = "DOShardedTagCache" },
    ]

[[migrations]]
    tag = "cache-primitives-v1"
    new_sqlite_classes = ["DOQueueHandler", "DOShardedTagCache"]

[ai]
    binding = "AI"

[version_metadata]
    binding = "CF_VERSION_METADATA"

[workers]
    name = "next-cf-app-og-image"
    main = ".open-next/server-functions/ogImage/index.mjs"
    compatibility_date = "2025-03-01"
    compatibility_flags = [
        "global_fetch_strictly_public",
    ]
    workers_dev = true

    [workers.assets]
        binding = "ASSETS"
        directory = ".open-next/assets"

    [[workers.d1_databases]]
        binding = "next_cf_app"
        database_name = "next-cf-app"
        database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
        migrations_dir = "./src/drizzle"

    [[workers.r2_buckets]]
        binding = "next_cf_app_bucket"
        bucket_name = "next-cf-app-bucket"

    [[workers.r2_buckets]]
        binding = "NEXT_INC_CACHE_R2_BUCKET"
        bucket_name = "next-cf-app-inc-cache"

    [workers.durable_objects]
        bindings = [
            { name = "NEXT_CACHE_DO_QUEUE", class_name = "DOQueueHandler" },
            { name = "NEXT_TAG_CACHE_DO_SHARDED", class_name = "DOShardedTagCache" },
        ]

    [workers.ai]
        binding = "AI"

    [workers.version_metadata]
        binding = "CF_VERSION_METADATA"

    [[workers.routes]]
        pattern = "/opengraph-image*"

[env.production]


[[env.production.d1_databases]]
    binding = "next_cf_app"
    database_name = "next-cf-app"
    database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
    migrations_dir = "./src/drizzle"

[[env.production.r2_buckets]]
    binding = "next_cf_app_bucket"
    bucket_name = "next-cf-app-bucket"

[[env.production.r2_buckets]]
    binding = "NEXT_INC_CACHE_R2_BUCKET"
    bucket_name = "next-cf-app-inc-cache"

[env.production.durable_objects]
    bindings = [
        { name = "NEXT_CACHE_DO_QUEUE", class_name = "DOQueueHandler" },
        { name = "NEXT_TAG_CACHE_DO_SHARDED", class_name = "DOShardedTagCache" },
    ]

[[env.production.migrations]]
    tag = "cache-primitives-v1"
    new_sqlite_classes = ["DOQueueHandler", "DOShardedTagCache"]

[env.production.ai]
    binding = "AI"

[env.production.version_metadata]
    binding = "CF_VERSION_METADATA"

[[env.production.workers]]
    name = "next-cf-app-og-image"
    main = ".open-next/server-functions/ogImage/index.mjs"
    compatibility_date = "2025-03-01"
    compatibility_flags = [
        "global_fetch_strictly_public",
    ]
    workers_dev = true

    [env.production.workers.assets]
        binding = "ASSETS"
        directory = ".open-next/assets"

    [[env.production.workers.d1_databases]]
        binding = "next_cf_app"
        database_name = "next-cf-app"
        database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
        migrations_dir = "./src/drizzle"

    [[env.production.workers.r2_buckets]]
        binding = "next_cf_app_bucket"
        bucket_name = "next-cf-app-bucket"

    [env.production.workers.ai]
        binding = "AI"

    [env.production.workers.version_metadata]
        binding = "CF_VERSION_METADATA"

    [[env.production.workers.routes]]
        pattern = "/opengraph-image*"
