name = "next-cf-app"
main = "worker.ts"
compatibility_date = "2025-03-01"
compatibility_flags = [
    "nodejs_compat",
    "global_fetch_strictly_public",
    "nodejs_als",
]
upload_source_maps = true

[assets]
    binding = "ASSETS"
    directory = ".open-next/assets"

[observability]
    enabled = true

[[rate_limits]]
    binding = "RATE_LIMITER"
    namespace = "rate-limiters/creem"

[[d1_databases]]
    binding = "next_cf_app"
    database_name = "next-cf-app"
    database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
    migrations_dir = "./src/drizzle"

[[r2_buckets]]
    binding = "next_cf_app_bucket"
    bucket_name = "next-cf-app-bucket"

[ai]
    binding = "AI"

[version_metadata]
    binding = "CF_VERSION_METADATA"

[env.production]

[[env.production.rate_limits]]
    binding = "RATE_LIMITER"
    namespace = "rate-limiters/creem"

[[env.production.d1_databases]]
    binding = "next_cf_app"
    database_name = "next-cf-app"
    database_id = "0a4563c7-3ffb-4805-a564-681f81562d31"
    migrations_dir = "./src/drizzle"

[[env.production.r2_buckets]]
    binding = "next_cf_app_bucket"
    bucket_name = "next-cf-app-bucket"

[env.production.ai]
    binding = "AI"
