# Production Environment Configuration
name: production

# Environment variables for production deployment
variables:
  NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
  CREEM_API_URL: ${{ secrets.CREEM_API_URL }}
  TRANSLATION_PROVIDER: gpt
  OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}

# Protection rules
protection_rules:
  required_reviewers: 2
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  require_up_to_date_branch: true
  enforce_admins: false