name: 'Setup Node.js and pnpm'
description: 'Setup Node.js with caching and configure pnpm package manager'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '8.15.9'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@36de12bed180fa130ed56a35e7344f2fa7a820ab
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - name: Setup pnpm cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Setup Node.js cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Output environment info
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "pnpm version: $(pnpm --version)"
        echo "pnpm store: $(pnpm store path --silent)"