name: 'Install and Heal'
description: 'Install dependencies with frozen lockfile first, then self-heal with dedupe and reinstall if needed.'
runs:
  using: 'composite'
  steps:
    - name: Install deps with self-healing
      shell: bash
      run: |
        set -euo pipefail
        if pnpm install --frozen-lockfile; then
          exit 0
        fi
        if git diff --quiet -- pnpm-lock.yaml; then
          echo "::notice::Transient install error; retrying with dedupe"
        else
          echo "::warning::Lockfile mismatch; attempting pnpm dedupe + reinstall"
        fi
        pnpm dedupe || true
        pnpm install --no-frozen-lockfile
        # Prevent lockfile drift from causing unrelated CI diffs
        git checkout -- pnpm-lock.yaml || true
