name: Auto Fix on Failure

on:
  workflow_run:
    workflows: ["CI", "Deploy Next.js App to Cloudflare"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  auto-fix:
    name: Attempt Auto Fixes
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps (frozen), then fallback to update lockfile
        id: deps
        run: |
          set -e
          if pnpm install --frozen-lockfile; then
            echo "lock_updated=false" >> "$GITHUB_OUTPUT"
          else
            echo "Frozen install failed; updating lockfile..."
            pnpm install --no-frozen-lockfile
            echo "lock_updated=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Apply Biome formatting
        run: pnpm exec biome format --write .

      - name: Apply Biome safe fixes (best effort)
        run: pnpm exec biome check . --write || true

      - name: Type check (capture errors but continue)
        run: pnpm exec tsc --noEmit || true

      - name: Commit changes (if any)
        id: commit
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH="autofix/${{ github.event.workflow_run.id }}"
          git checkout -B "$BRANCH"
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "chore(auto-fix): formatting/lockfile updates after failed run ${{ github.event.workflow_run.id }}"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create pull request
        if: steps.commit.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref_name == 'main' && format('autofix/{0}', github.event.workflow_run.id) || format('autofix/{0}', github.event.workflow_run.id) }}
          title: "chore(auto-fix): apply automated fixes after failed run #${{ github.event.workflow_run.id }}"
          commit-message: "chore(auto-fix): apply automated fixes after failed run #${{ github.event.workflow_run.id }}"
          body: |
            This PR was opened automatically after a failed workflow run.

            - Source workflow: `${{ github.event.workflow_run.name }}` run #${{ github.event.workflow_run.run_number }}
            - URL: ${{ github.event.workflow_run.html_url }}

            Applied actions:
            - pnpm install with lockfile update (if needed): `${{ steps.deps.outputs.lock_updated }}`
            - biome format --write .
            - biome check . --write (best effort)
            - tsc --noEmit (diagnostic)

            Merge this PR to re-trigger CI/CD.
          labels: autofix,ci
          delete-branch: true

