name: Build

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Determine changed files
    runs-on: ubuntu-latest
    outputs:
      docs_only: ${{ steps.diff.outputs.docs_only }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 2
      - name: Compute docs-only flag
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" != "push" ]; then
            echo "Non-push event detected; forcing docs_only=false"
            echo "docs_only=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          base="${{ github.event.before }}"
          if [ -z "${base}" ]; then
            base=$(git rev-list HEAD~1 -n 1 || true)
          fi
          if [ -z "${base}" ]; then
            echo "docs_only=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          files=$(git diff --name-only "${base}"...HEAD | tr -d '\r' || true)
          echo "Changed files:"; echo "$files"
          if [ -z "${files}" ]; then
            echo "docs_only=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Anything outside docs/ or README.md is considered non-docs
          non_docs=$(echo "$files" | grep -Ev '^(README\.md|docs/)' || true)
          if [ -z "${non_docs}" ]; then
            echo "docs_only=true" >> "$GITHUB_OUTPUT"
          else
            echo "docs_only=false" >> "$GITHUB_OUTPUT"
          fi

  sonarcloud:
    name: SonarCloud
    needs: changes
    if: needs.changes.outputs.docs_only != 'true' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs-only:
    name: Docs-only fast path
    needs: changes
    if: needs.changes.outputs.docs_only == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs-only change detected. Skipping tests and SonarCloud scan."
