name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Determine changed files
    runs-on: ubuntu-latest
    outputs:
      docs_only: ${{ steps.diff.outputs.docs_only }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 2
      - name: Compute docs-only flag
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          base="${{ github.event.before }}"
          if [ -z "${base}" ]; then
            base=$(git rev-list HEAD~1 -n 1 || true)
          fi
          if [ -z "${base}" ]; then
            echo "docs_only=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          files=$(git diff --name-only "${base}"...HEAD | tr -d '\r' || true)
          echo "Changed files:"; echo "$files"
          if [ -z "${files}" ]; then
            echo "docs_only=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Anything outside docs/ or README.md is considered non-docs
          non_docs=$(echo "$files" | grep -Ev '^(README\.md|docs/)' || true)
          if [ -z "${non_docs}" ]; then
            echo "docs_only=true" >> "$GITHUB_OUTPUT"
          else
            echo "docs_only=false" >> "$GITHUB_OUTPUT"
          fi

  sonarcloud:
    name: SonarCloud
    needs: changes
    if: needs.changes.outputs.docs_only != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Setup pnpm
        uses: pnpm/action-setup@36de12bed180fa130ed56a35e7344f2fa7a820ab
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test (Vitest with coverage lcov)
        run: >
          pnpm exec vitest run --coverage
          --coverage.reporter=lcov
          --coverage.reporter=json-summary
          --coverage.reporter=text

      - name: Ensure coverage exists
        run: |
          if [ ! -f coverage/lcov.info ]; then
            echo "coverage/lcov.info not found"; exit 1; fi

        docs-only:
          name: Docs-only fast path
          needs: changes
          if: needs.changes.outputs.docs_only == 'true'
          runs-on: ubuntu-latest
          steps:
            - run: echo "Docs-only change detected. Skipping tests and SonarCloud scan."
