name: CI

on:
  push:
    branches: ["**"]
    paths-ignore:
      - README.md
      - docs/**
  pull_request:
    branches: ["**"]
    paths-ignore:
      - README.md
      - docs/**

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', 'package.json', 'tsconfig.json', 'tsconfig.*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Run i18n normalization
        run: pnpm run fix:i18n

      - name: Ensure i18n is normalized (no diff)
        run: |
          git diff --exit-code || (echo "i18n files not normalized. Run 'pnpm run fix:i18n' and commit changes." && exit 1)

      - name: Lint (Biome)
        run: pnpm exec biome check .

      - name: Type check (tsc)
        run: pnpm exec tsc --noEmit

      - name: Test (Vitest)
        run: pnpm test

      - name: Build (Next.js)
        run: pnpm build
