name: CI

on:
  # 甯歌 CI锛氬湪闄?main 澶栫殑鍒嗘敮涓婅繍琛岋紱閬垮厤涓庨儴缃插伐浣滄祦閲嶅
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs/**
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs/**
  # 鍏佽琚叾浠栧伐浣滄祦澶嶇敤锛坮eusable workflow锛?  workflow_call:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'
  # 鎻愪緵缁?Next.js 棰勬覆鏌撲笌 SEO 閫昏緫鐨勫熀纭€ URL锛堜粨搴?Actions Variables 鍙鐩栵級
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL || 'http://localhost:3000' }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: |
          set -euo pipefail
          if pnpm install --frozen-lockfile; then
            exit 0
          fi
          echo "::warning::Frozen install failed; attempting pnpm dedupe + reinstall"
          pnpm dedupe || true
          pnpm install --no-frozen-lockfile

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', 'package.json', 'tsconfig.json', 'tsconfig.*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Run i18n normalization
        run: pnpm run fix:i18n

      - name: Ensure i18n is normalized (no diff)
        run: |
          git diff --exit-code || (echo "i18n files not normalized. Run 'pnpm run fix:i18n' and commit changes." && exit 1)

      - name: Lint (Biome)
        run: pnpm exec biome check .

      - name: Type check (tsc)
        run: pnpm exec tsc --noEmit

      - name: Test (Vitest)
        run: pnpm test

      - name: Show NEXT_PUBLIC_APP_URL (diagnostic)
        run: |
          echo "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL"

      - name: Build (Next.js)
        run: pnpm build

