name: CI

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs/**
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs/**
  workflow_call:

env:
  NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL || 'http://localhost:3000' }}

jobs:
  lint-docs:
    name: Lint & docs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - &load-config
        name: Load workflow configuration
        uses: ./.github/actions/load-workflow-config

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache-key-suffix: "-ci-${{ env.NODE_VERSION }}"

      - &install
        name: Install dependencies (composite)
        uses: ./.github/actions/install-and-heal

      - name: Run i18n normalization
        run: pnpm run fix:i18n

      - name: Ensure i18n is normalized (no diff)
        run: |
          git diff --exit-code -- src/i18n/messages || (echo "i18n files not normalized. Run 'pnpm run fix:i18n' and commit changes." && exit 1)

      - name: Lint (Biome)
        run: pnpm exec biome check .

      - name: Generate OpenAPI snapshot
        run: pnpm run openapi:generate

      - name: Verify OpenAPI snapshot
        run: pnpm run openapi:check

      - name: Lint OpenAPI schema (Spectral)
        run: pnpm run openapi:lint

      # Removed docs consistency step to speed up CI and avoid non-critical failures

      - name: Link check (local markdown)
        run: pnpm run check:links

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - *checkout
      - *load-config
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache-key-suffix: "-typecheck-${{ env.NODE_VERSION }}"
      - *install
      - name: Type check (tsc)
        run: pnpm exec tsc --noEmit

  supply-chain:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'pull_request'
    steps:
      - *checkout
      - *load-config
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache-key-suffix: "-security"

      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@bf2dc8e55639c1e091e9b45970152e4313705814
        with:
          verbose: "true"
          redaction: "true"
          args: "detect --source ."

      - name: Check for duplicate dependencies
        run: |
          echo "::group::Checking for duplicate dependencies"
          if pnpm dedupe --check; then
            echo "✅ No duplicate dependencies found"
          else
            echo "::warning::Duplicate dependencies detected. Consider running 'pnpm dedupe'"
          fi
          echo "::endgroup::"

      - name: Security audit (enhanced)
        run: |
          echo "::group::Running security audit on production dependencies"

          attempts=0
          max_attempts=3
          while true; do
            attempts=$((attempts + 1))
            if audit_output=$(pnpm audit --prod --audit-level high --json 2>/tmp/audit-error.log); then
              break
            fi
            if grep -qiE 'ENOTFOUND|ETIMEDOUT|ECONNRESET' /tmp/audit-error.log && [[ $attempts -lt $max_attempts ]]; then
              echo "::warning::pnpm audit network error (attempt $attempts/$max_attempts), retrying in 5s"
              sleep 5
              continue
            fi
            cat /tmp/audit-error.log >&2 || true
            exit 1
          done

          high_vulns=$(echo "$audit_output" | jq -r '.vulnerabilities | length' 2>/dev/null || echo "0")

          if [[ "$high_vulns" -gt 0 ]]; then
            echo "::error::Found $high_vulns high/critical vulnerabilities:"
            echo "$audit_output" | jq '.'
            exit 1
          fi

          if ! pnpm audit --prod --audit-level moderate 2>/dev/null | tee /tmp/audit-moderate.log | grep -q "vulnerabilities"; then
            echo "✅ No production vulnerabilities found"
          else
            echo "::warning::Moderate vulnerabilities detected. See details above."
          fi

          echo "::endgroup::"

      - name: License compliance check
        run: |
          echo "::group::Checking license compliance"
          if command -v npx >/dev/null 2>&1; then
            npx license-checker --summary --excludePrivatePackages || echo "::warning::License check failed"
          else
            echo "::warning::License checker not available"
          fi
          echo "::endgroup::"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - lint-docs
      - typecheck
    steps:
      - *checkout
      - *load-config
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache-key-suffix: "-build"
      - *install

      - name: Cache Next.js build cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', 'package.json', 'tsconfig.json', 'tsconfig.*.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Show NEXT_PUBLIC_APP_URL (diagnostic)
        run: echo "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL"

      - name: Build (Next.js)
        run: pnpm build

      - name: Archive Next.js build output
        run: |
          set -euo pipefail
          files=()
          for dir in .next/standalone .next/static .next/cache; do
            if [[ -d "$dir" ]]; then
              files+=("$dir")
            fi
          done
          if [[ ${#files[@]} -eq 0 ]]; then
            echo "::warning::No Next.js build output found to archive"
            exit 0
          fi
          tar -czf next-build.tar.gz "${files[@]}"

      - name: Upload Next.js build artifacts
        if: hashFiles('next-build.tar.gz') != ''
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: next-build
          path: next-build.tar.gz
          retention-days: 3
