name: Close CI/CD Failure Issue on Success

on:
  workflow_run:
    workflows: ["CI", "Deploy Next.js App to Cloudflare"]
    types: [completed]

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: read

jobs:
  close-tracker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build recovery message
        id: msg
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const body = [
              `✅ Workflow "${run.name}" #${run.run_number} succeeded`,
              `Run: ${run.html_url}`,
              `Event: ${run.event}`,
              run.head_commit?.id ? `Commit: ${run.head_commit.id.slice(0,7)} — ${run.head_commit.message}` : undefined,
            ].filter(Boolean).join('\n');
            core.setOutput('body', body);

      - name: Close CI/CD Failure Tracker issue (if any)
        uses: actions/github-script@v7
        env:
          BODY: ${{ steps.msg.outputs.body }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const title = 'CI/CD Failure Tracker';
            // Find open issues with the label and title
            const { data: issues } = await github.rest.issues.listForRepo({ owner, repo, state: 'open', labels: 'ci-failure' });
            const target = issues.find(i => i.title === title);
            if (!target) {
              core.info('No open CI/CD Failure Tracker issue found. Nothing to close.');
              return;
            }
            // Comment then close
            await github.rest.issues.createComment({ owner, repo, issue_number: target.number, body: process.env.BODY });
            await github.rest.issues.update({ owner, repo, issue_number: target.number, state: 'closed' });
            core.info(`Closed issue #${target.number}`);

