name: Semgrep

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Semgrep (auto config)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        env:
          SEMGREP_TIMEOUT: 300
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif

