name: Semgrep

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      # If no token or PR from fork, run public rules without publishing
      - name: Run Semgrep (public ruleset p/ci)
        if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) || secrets.SEMGREP_APP_TOKEN == '' }}
        uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          config: p/ci
          generateSarif: true
        env:
          SEMGREP_TIMEOUT: 300

      # With token and non-fork context, use Semgrep App auto configuration and publish
      - name: Run Semgrep (auto config)
        if: ${{ secrets.SEMGREP_APP_TOKEN != '' && !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
        uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          config: auto
          generateSarif: true
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        env:
          SEMGREP_TIMEOUT: 300

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@a8d1ac45b9a34d11fe398d5503176af0d06b303e
        if: ${{ always() && hashFiles('semgrep.sarif') != '' }}
        with:
          sarif_file: semgrep.sarif
